# This file contains configuration specific for this repository that are different from the default Ekylibre style guide

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/first_runs/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'lib/generators/**/*'
    - 'lib/procedo/formula/language.rb'
    - 'lib/working_set/query_language.rb'
    - 'node_modules/**/*'
    - 'plugins/**/*'
    - 'plugins-disabled/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# We disable this for now. 1500 offenses as of 01/02/2021
Layout/LineLength:
  Enabled: false

# Too many offenses to enable this for now.
Style/StringLiterals:
  Enabled: false

# Do not encourage the use of modifiers
Style/WhileUntilModifier:
  Enabled: false